### Example: Sequential operations in Python
Consider the following Python code that demonstrates how a CPU would handle a series of sequential
operations, such as iterating through a list and performing a calculation on each item. Since
CPUs are optimized for single-threaded operations, this is a typical example of the type of task where
they excel.

In [2]:
numbers = [1,2,3,4,5,6,7,8,9]
squared_numbers = []

for number in numbers:
    squared_numbers.append(number ** 2)

print(squared_numbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In this case, the CPU performs each iteration of the loop one after the other in a linear sequence,
quickly handling each task.

Example 2: Parallel operations in Python using TensorFlow
In this example, we will demonstrate how to use TensorFlow to perform parallel matrix operations on a GPU. TensorFlow automatically detects available GPUs and offloads operations to them.

In [4]:
! pip install tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 620.8/620.8 MB 70.0 kB/s  1:28:02m0:00:0103:33
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 60.8 kB/s  0:01:39m0:00:0300:07
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 60.8 kB/s  0:01:17 eta 0:00:04
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 69.5 kB/s  0:01:22m0:00:0100:05
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 55.4 kB/s  0:01:19 eta 0:00:04
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 52.1 kB/s  0:00:26 eta 0:00:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 50.5 kB/s  0:07:32m0:00:0300:15
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 53.0 kB/s  0:05:18m0:00:0300:15
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 43.4 kB/s  0:02:18m0:00:0200:08
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26/26 [tensorflow]6 [tensorflow]-py]


In [5]:
import tensorflow as tf
# Create a large matrix
matrix = tf.random.uniform((1000,1000))
print(matrix)
# Perform a matrix multiplication (parallelized on the GPU)
result = tf.matmul(matrix, matrix)
tf.print(result)

2025-09-26 00:18:22.287294: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


tf.Tensor(
[[0.13004518 0.84748614 0.2270875  ... 0.7458832  0.99783456 0.5731169 ]
 [0.08732259 0.70059323 0.23242676 ... 0.7435374  0.53951645 0.8577293 ]
 [0.10347593 0.14106536 0.81996095 ... 0.8034626  0.00634098 0.1147083 ]
 ...
 [0.30464292 0.79907846 0.77350307 ... 0.95706356 0.30141973 0.77926624]
 [0.3281932  0.5348165  0.3558544  ... 0.88482213 0.19720232 0.6675515 ]
 [0.8592788  0.0202378  0.61015797 ... 0.7103808  0.74298215 0.2031815 ]], shape=(1000, 1000), dtype=float32)
[[237.677307 242.357559 241.551941 ... 255.651245 249.1474 241.301529]
 [249.864243 245.160522 251.838593 ... 268.313385 253.124878 247.757324]
 [248.079971 247.996582 248.186905 ... 263.282562 257.262878 247.419128]
 ...
 [246.074677 249.738266 244.21106 ... 261.871704 258.541809 239.883972]
 [245.866302 251.497 249.791916 ... 267.468079 257.267151 246.39621]
 [233.316971 238.451 239.813828 ... 253.885117 243.204727 239.814]]


W0000 00:00:1758817104.139776   46871 gpu_device.cc:2342] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In this case, TensorFlow automatically uses the GPU to accelerate the matrix multiplication.

## Example 3: Parallel operations in Python using PyTorch and GPU
This example demonstrates the use of a GPU to perform parallel operations using PyTorch, a popular deep-learning framework that provides GPU acceleration. In deep-learning, we perform matrix operations using PyTorch’s CUDA support to leverage the GPU.

In [ ]:
! pip install torch
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

   ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/766.6 MB 1.8 MB/s eta 0:06:53

In [9]:
! uname -a

Darwin Sanjeebs-MacBook-Pro.local 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:29 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6000 arm64
